Prevent apache docker entrypoint script from exiting if plack already enabled

diff --git a/docker/build/templates/docker-entrypoint-apache.sh.j2 b/docker/build/templates/docker-entrypoint-apache.sh.j2
--- a/docker/build/templates/docker-entrypoint-apache.sh.j2
+++ b/docker/build/templates/docker-entrypoint-apache.sh.j2
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 set -e
 
-koha-plack --enable {{ koha_instance_name }}
+koha-plack --enable {{ koha_instance_name }} || true # Exit status 1 when already enabled, ignore this
 
 # If first arg starts with "-" OR no args provided → run apache
 if [[ $# -eq 0 || "$1" == -* ]]; then
